version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: autorizaciones
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    environment:
      DB_NAME: autorizaciones
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: "5432"
      DEBUG: "True"
      CORS_ALLOW_ALL: "True"
      DJANGO_ADMIN_USER: admin
      DJANGO_ADMIN_PASS: admin123
      DJANGO_ADMIN_EMAIL: admin@example.com
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  pgdata:
